### ISSUE TITLE
本番環境DBの設定について

### ISSUE THREAD

**Issue by YAN-cyber-ux** [YAN-cyber-ux/Busi_neer#7]
- 質問内容・実現したいこと

　本番環境でデータベースが使えるようにしたい。

- 現状発生している問題・エラーメッセージ

　環境構築のトラブルを最小限に防ぐため、railsチュートリアルと同様の環境(Ruby 3.2.2, Rails 7.0.4.3)で開発をしていました。
チュートリアルの第7章の最後に本番環境でデータベースを設定する部分があり、各種ファイルの設定やコマンドを書かれた通りに実行したのですが、期待通りに動作せず、困っています。

　諸事情によりPostgreSQLは有料プラン(starter)を選択していますが、それ以外は全く同条件で行なっております。

- どの処理までうまく動いているのか
　Webアプリケーションのデプロイ自体は成功しています。
　ただ、ユーザー登録を行う段階になるとエラーが発生します。

- 該当のソースコード
　上記エラーが起きた際、Renderのログには以下のように表示されました。
```
F, [2024-02-15T15:23:14.202417 #70] FATAL -- : [aa0c4490-15ec-4077-886e-0b422266298c]   
[aa0c4490-15ec-4077-886e-0b422266298c] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
```

- エラーから考えられる原因と 試したこと

　railsチュートリアルには特に記載はありませんが、そもそも本番環境でDBを作成するコマンドを実行していないことが原因なのではと考えました。

そのため、rails db:create RAILS_ENV=production　を実行したところ、続いて下記のエラーが出ました。

```
　rails aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile. (LoadError)
```

このエラーに関して、ChatGPT4を使用した際のプロンプトとその結果は以下のようになりました。

User
私はプログラミング初学者です。
未経験からWebエンジニア転職を目指しています。
以下の条件で学習しています。
#サーバーサイド:Ruby on Rails 7系
　　Ruby 3.2.2    Rails 7.0.4.3
#Webアプリケーションサーバ: Render
データベースサーバー:  PostgreSQL(in Render)

rails db:create RAILS_ENV=production　を実行したところ、以下のエラーが出ました。解決方法を教えてください。
                            
rails aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile. (LoadError)

GPT
エラーメッセージによると、`postgresql`用のActive Recordアダプターをロードしようとした際に失敗しており、「pg」というgemがバンドルに含まれていないため、Gemfileに追加する必要があるとのことです。`pg` gemは、Ruby on RailsプロジェクトでPostgreSQLデータベースを使用するために必要なgemです。以下の手順で問題を解決できます。

1. **Gemfileにpg gemを追加する**:
   - プロジェクトのルートディレクトリにある`Gemfile`を開きます。
   - `gem 'pg'`という行を追加します。すでに存在する場合は、このステップをスキップしてください。
   - 追加する際には、特定のバージョンを指定することもできますが、最初は最新バージョンを使うのが一般的です。

2. **Bundleを更新する**:
   - ターミナルまたはコマンドプロンプトで、プロジェクトのルートディレクトリに移動します。
   - `bundle install`を実行して、`pg` gemを含めた依存関係をインストールします。

3. **データベースを作成する**:
   - インストール後、再度`rails db:create RAILS_ENV=production`を実行してみてください。

これで、`pg` gemが正しくインストールされ、PostgreSQLデータベースを使ったRailsアプリケーションのセットアップが完了するはずです。

問題が解決しない場合は、以下の点を確認してください。

- **RubyのバージョンとRailsのバージョンが互換性があるかどうか**: 使用しているRubyとRailsのバージョンが互換性があることを確認してください。
- **環境変数の設定**: `RAILS_ENV=production`としている場合、本番環境のデータベース設定が`config/database.yml`に正しく設定されているか確認してください。
- **PostgreSQLサーバーの稼働**: PostgreSQLサーバーが稼働しており、正しく設定されていることを確認してください。

これらのステップを実行しても問題が解決しない場合は、エラーメッセージの詳細や、実行したコマンド、環境の詳細（Rubyのバージョン、Railsのバージョン、OSの情報など）を提供してください。それによって、さらに具体的なアドバイスが可能になります。

参考までに、Gemfileでは、チュートリアルに合わせる形でgem "pg"の設定自体は行なっております。

```
group :production do
  gem "pg", "1.3.5"
end
```

　自分と同じ条件でデプロイをしている技術記事も探してみたのですが、railsの系やrubyのバージョンで自分の状況に近いものが見つかりませんでした。

　個人的にもう少し調べてみようと思いますが、少しでもヒントになりそうなことがありましたら教えていただけますと幸いです。

　情報が不足している部分がありましたらご指摘ください。

　長文失礼しました。

**Comment by Tsuchiya2** [comment]
対象のアプリケーションのデータベース(Heroku)はMiniなど有料化は済んでいますでしょうか？

https://jp.heroku.com/pricing#data-services

**Comment by YAN-cyber-ux** [comment]
今現在はRenderを使用しているのですが、
DBサーバは有料プラン(starter)、
APサーバーは無料プラン(Free)を使用しております。

**Comment by YAN-cyber-ux** [comment]
お疲れ様です。
こちらの問題ですが、結果的に解決いたしました。
大変お手数おかけしました。

理由としては、アプリ側でのビルドスクリプト(bin/render-build.sh)とRender側でのビルドコマンドの設定がうまくいっていなかったことがありました。

ご対応ありがとうございました。
もしまた何か不具合ありましたら質問させていただければと思います。
